dependencies:
  - name: "nginx-ingress"
    version: "0.28.2"
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: "grafana"
    version: "1.9.1"
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "prometheus"
    version: "7.4.0"
    repository: https://kubernetes-charts.storage.googleapis.com/