dependencies:
  - name: "nginx-ingress"
    version: "0.28.2"
    repository: https://kubernetes-charts.storage.googleapis.com
    import-values:
      - child: tcp
        parent: tcp
      - child: controller.image
        parent: controller.image