# Default values for hagnix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#types of Cloud supported GKE and Local
cloud: "Local"
deploy: "production"

tcp: {
  81: "hagnix/rotmgserver:81",
  2050: "hagnix/rotmgwserver:2050"
}

backend:
  node: # hagnix/nodeback
    #image: gcr.io/white-script-214013/hagnix/nodeback
    image: gcr.io/white-script-214013/hagnix/nodeback
    port: 3000
    replicas: 1
    autoscaling:
      use: true
      minReplicas: 1
      maxReplicas: 10
  mysql:
    port: 3306
    image: percona:5.6
    database: rotmgprod
    user: dangerous
    host: mysql
  redis:
    port: 6379
    host: redis
    image: bitnami/redis:4.0
  mongodb:
    image: bitnami/mongodb:4.0
    root: root
    host: mongodb
    database: production
    port: 27017
  rotmgserver:
    replicas: 1
    #image: gcr.io/white-script-214013/hagnix/server
    image: gcr.io/white-script-214013/hagnix/server:1.1.2
    port: 81
    autoscaling:
      use: true
      minReplicas: 1
      maxReplicas: 3
    disableRegister: true
    configPath: "config"
    config: { 
      'server.cfg': "I1NlcnZlckNvbmZpZwpwb3J0OjgwCnZlcmlmeUVtYWlsOmZhbHNlCnNlcnZlckRvbWFpbjpodHRwOi8vYzQ1My5wdwojc2VydmVyRW1haWw6CiNzZXJ2ZXJFbWFpbFBhc3N3b3JkOgojc210cEhvc3Q6CiNzbXRwUG9ydDoKIwojRGF0YWJhc2UgQ29uZmlnCiMKZGJfaG9zdDoxMjcuMC4wLjEKZGJfZGF0YWJhc2U6cm90bWdwcm9kCmRiX3VzZXI6cm9vdApkYl9hdXRoOnJvb3QKIwojU2VydmVycwojCnN2ck51bTozCiNzdnIwTmFtZTpUZXN0aW5nIFNlcnZlcgojc3ZyMEFkcjo2OS4xNDAuMS4yMDMKI3N2cjBMb2NhdGlvbjpBcmxpbmd0b24sIFZpcmdpbmlhLCBVU0EKc3ZyME5hbWU6TG9jYWxob3N0CnN2cjBBZHI6MTI3LjAuMC4xCnN2cjBMb2NhdGlvbjpBcmxpbmd0b24sIFZpcmdpbmlhLCBVU0EKc3ZyMU5hbWU6SGFnbml4CnN2cjFBZHI6MzUuMjI0LjE3Ny4xNTMKc3ZyMk5hbWU6SGFnb3JvbW8Kc3ZyMkFkcjozNS4yMjQuMTc3LjE1Nwo="
    }
  rotmgwserver:
    port: 2050
    replicas: 1
    #image: gcr.io/white-script-214013/hagnix/wserver
    image: gcr.io/white-script-214013/hagnix/wserver:1.0