# Default values for hagnix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#types of Cloud supported GKE and Local
#Disk necessary: mysql-disk and mongo-disk
cloud: "Local"
deploy: "production"
debug: "true"

backend:
  credentials:
    create_default: true

  node: # hagnix/nodeback
    #image: gcr.io/white-script-214013/hagnix/nodeback
    image: dangerousplay/hagnix-nodeback:latest
    port: 3000
    replicas: 1
    #"http://www.hagnix.tk"
    cors_origin: "http://localhost:4200"
    autoscaling:
      use: true
      minReplicas: 1
      maxReplicas: 10
  mysql:
    port: 3306
    image: percona:5.6
    database: rotmgprod
    user: dangerous
    host: mysql
  redis:
    port: 6379
    host: redis
    image: redis:4
    password: "S4512123ASFzaxkltbn3"
  mongodb:
    image: bitnami/mongodb:4.1
    root: root
    host: mongodb
    database: production
    port: 27017
  rotmgserver:
    replicas: 1
    #image: gcr.io/white-script-214013/hagnix/server
    image: dangerousplay/hagnix-server
    port: 81
    autoscaling:
      use: true
      minReplicas: 1
      maxReplicas: 3
    disableRegister: true
    config:
       server : "I1NlcnZlckNvbmZpZwpwb3J0OjgwCnZlcmlmeUVtYWlsOmZhbHNlCnNlcnZlckRvbWFpbjpodHRwOi8vYzQ1My5wdwojc2VydmVyRW1haWw6CiNzZXJ2ZXJFbWFpbFBhc3N3b3JkOgojc210cEhvc3Q6CiNzbXRwUG9ydDoKIwojRGF0YWJhc2UgQ29uZmlnCiMKZGJfaG9zdDoxMjcuMC4wLjEKZGJfZGF0YWJhc2U6cm90bWdwcm9kCmRiX3VzZXI6cm9vdApkYl9hdXRoOnJvb3QKIwojU2VydmVycwojCnN2ck51bToxCiNzdnIwTmFtZTpUZXN0aW5nIFNlcnZlcgojc3ZyMEFkcjo2OS4xNDAuMS4yMDMKI3N2cjBMb2NhdGlvbjpBcmxpbmd0b24sIFZpcmdpbmlhLCBVU0EKc3ZyME5hbWU6SGFnbml4CnN2cjBBZHI6MzUuMTg0LjIyOC4xODAKc3ZyMU5hbWU6SGFnbml4CnN2cjFBZHI6MzUuMTg0LjIyOC4xODA="
  rotmgwserver:
    port: 2050
    replicas: 1
    #image: gcr.io/white-script-214013/hagnix/wserver
    image: dangerousplay/hagnix-wserver:latest
    whitelist: false


frontend:
  angular:
    #"http://www.hagnix.tk:3000"
    base_url: "http://localhost:3000"
    image: dangerousplay/hagnix-angular
    autoscaling:
      use: true
      minReplicas: 1
      maxReplicas: 3


nginx-ingress:
  controller:
    name: controller
    image:
      repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64
      tag: "0.17.0"
      pullPolicy: IfNotPresent

    defaultBackendService: "hagnix/website"

  defaultBackend:
    enabled: false


  tcp: {
    81: "hagnix/rotmgserver:81",
    2050: "hagnix/rotmgwserver:2050",
    3000: "hagnix/nodeback:3000",
    82: "hagnix/hagnix-traefik-dashboard:80",
    83: "hagnix/hagnix-prometheus-server:9090",
  }

prometheus:
  rbac:
    create: true

  nodeExporter:
#    image:
#      repository: prom/node-exporter
#      tag: v0.15.2

  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: ['traefik:8080','cadvisor:8080','node-exporter:9100']
