apiVersion: v1
kind: ConfigMap
metadata:
    name: mongodb
    namespace: {{ .Release.Namespace }}
    labels:
      app: mongodb
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
    user.sh: |
        mongo production -u $MONGODB_USERNAME -p $MONGODB_PASSWORD --eval 'var document = { CPF : "04908861082", CEP : "92410535", password : "$2b$10$DTZLpk8sX.Uf3kKtrmXYcuxUN4O4BiWB1mNH09LgcMIZ7LVxQTxM2", name : "Davi Henrique", house : "587", complement : "", bairro : "Igara", street : "Doutor Alfredo Ângelo Filho", admin : true, roles : [], email : "gm.davi.gm@live.com", login : { attempts : 0, lastAttempt : new Date(), locked : false } }; db.users.insertOne(document);'