apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.backend.mysql.host }}
  labels:
    app: mysql
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app: mysql
  ports:
    - port: {{ .Values.backend.mysql.port }}
  type: NodePort