apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.backend.redis.host }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: {{ .Values.backend.redis.port }}
  type: NodePort