apiVersion: v1
kind: Service
metadata:
  name: rotmgserver
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: rotmgserver
spec:
  selector:
    app: rotmgserver
  ports:
  - port: {{ .Values.backend.rotmgserver.port }}
    targetPort: 80
  {{ if eq .Values.deploy "production" -}}
  type: NodePort
  {{- else -}}
  type: LoadBalancer
  {{- end }}