apiVersion: v1
kind: Service
metadata:
  name: rotmgwserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: rotmgwserver
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app: rotmgwserver
  ports:
  - port: {{ .Values.backend.rotmgwserver.port }}
    targetPort: 2050
  {{ if eq .Values.deploy "production" -}}
  type: NodePort
  {{- else -}}
  type: LoadBalancer
  {{- end }}
