apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  MONGO_PASSWORD: dTg1ZVJ4RXRFZjQ2YlNzTA==
  REDIS_PASSWORD: {{ .Values.backend.redis.password | b64enc }}
  MYSQL_ROOT_PASSWORD: NE1XQ2c0M1RjN1paZ0Y2WQ==
  MYSQL_PASSWORD: NG5SVGVQNWpMVGhuN3A5Sw==