{{- if .Values.backend.rotmgserver.config }}
apiVersion: v1
kind: Secret
metadata:
  name: server-config
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
{{ toYaml .Values.backend.rotmgserver.config | indent 2 }}
{{- end }}