apiVersion: apps/v1
kind: Deployment
metadata:
    name: website
    namespace: {{ .Release.Namespace }}
    labels:
        app: website
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
    replicas: 1
    template:
        metadata:
            name: website
            labels:
              app: website
              heritage: {{ .Release.Service | quote }}
              release: {{ .Release.Name | quote }}
              chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        spec:
            containers:
                - name: website
                  image: {{ .Values.frontend.angular.image }}
                  imagePullPolicy: IfNotPresent
                  ports:
                    - containerPort: 80
                  env:
                    - name: BASE_URL
                      value: {{ .Values.frontend.angular.base_url }}
                  readinessProbe:
                    initialDelaySeconds: 10
                    tcpSocket:
                      port: 80
                  livenessProbe:
                    initialDelaySeconds: 5
                    tcpSocket:
                      port: 80
            restartPolicy: Always
    selector:
        matchLabels:
            app: website
