apiVersion: v1
kind: Service
metadata:
    name: website
    namespace: {{ .Release.Namespace }}
    labels:
        app: website
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
    selector:
        app: website
    ports:
        - port: 80
    type: NodePort